### ISSUE TITLE
최솟값(10868) 오류 원인을 모르겠음.

### ISSUE THREAD

**Issue by baesy0** [studyalgo/Seoyoung#6]
문제에 있는 예시 입력을 똑같이 입력했는데 출력이 다름
입력 예시
```
1 10
3 5
6 9
8 10
```
출력 예시
```
5
38
20
5
```
내 출력
```
5
38
5
5
```

**Comment by baesy0** [comment]
도움!

**Comment by kybin** [comment]
start - end, left - right가 서로 부분만 겹칠때의 처리가 빠져있는 것 아닌가요?
이럴때 중간값 기준으로 왼쪽 절반에서 값을 검색할지 그리고 오른쪽 절반에서 검색할지 각각 검사해야하는데  현재 코드는 left - right안에 start - end가 완전히 포함될 때와 똑같이 처리되도록 되어있네요.

**Comment by kybin** [comment]
README를 제외하고는 이 이슈와 문제를 내는 페이지, 코드가 서로 링크가 되어있지 않아 살펴보기가 어려웠어요. 코드 안에 해당 문제를 내는 페이지가 주석 형태로 쓰여있다면 더 좋을것 같습니다.

**Comment by baesy0** [comment]
오 용빈님이다! 한 번 체크해볼게요. 감사해요!
좋은 피드백도 고마워요! 다음에 이슈쓸 때(= 아마 도움을 청할 때ㅋㅋ) 참고할게요:D

**Comment by kybin** [comment]
네넹!

**Comment by baesy0** [comment]
해결!
```cpp
int findMinimum(vector<int> &tree, int node, int start, int end, int left, int right){
    int l, r;
    if(start == end) return tree[node];
    if(left > end || right < start) return 1e9;
    if(left >= start && right <= end){
        l = findMinimum(tree, node*2, start, (start+end)/2, left, right);
        r = findMinimum(tree, node*2+1, (start+end)/2 + 1, end, left, right);
        return l < r? l : r;
    }
    l = findMinimum(tree, node*2, start, (start+end)/2, left, right);
    r = findMinimum(tree, node*2+1, (start+end)/2 + 1, end, left, right);
    return l < r? l : r;
}
```
위 함수에서 if문으로 조건을 거를 때, 순서의 문제였음.
위 함수에서는 아래와 같은 순서로 조건을 검사하고 있는데
1. 리프노드인가
2. left-right가 start-end범위를 완전히 벗어났는지
3. left-right가 start-end범위 안에 완전히 포함되는지
4. 나머지 경우

리프노드이면서 left-right가 start-end범위에 들지 않는 경우,
범위에 들지 않으므로 큰 수를 반환해야하는데,
리프노드라는 조건을 먼저 체크하는 바람에 해당 노드의 값을 반환하게 된다.

1번과 2번의 순서를 바꿔서 해결!

**Comment by baesy0** [comment]
근데 백준에 제출하면 시간초과 뜸ㅎ 또륵...
